In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\mayan\Downloads\NLP data\fake_or_real_news.csv')

In [3]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [4]:
 X = df.drop(['label'],axis=1)

In [5]:
X

title  \
0                          You Can Smell Hillary’s Fear   
1     Watch The Exact Moment Paul Ryan Committed Pol...   
2           Kerry to go to Paris in gesture of sympathy   
3     Bernie supporters on Twitter erupt in anger ag...   
4      The Battle of New York: Why This Primary Matters   
...                                                 ...   
6330  State Department says it can't find emails fro...   
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...   
6332  Anti-Trump Protesters Are Tools of the Oligarc...   
6333  In Ethiopia, Obama seeks progress on peace, se...   
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                   text  
0     Daniel Greenfield, a Shillman Journalism Fello...  
1     Google Pinterest Digg Linkedin Reddit Stumbleu...  
2     U.S. Secretary of State John F. Kerry said Mon...  
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...  
4     It's primary day in New York and front-runners...  
...                                                 ...  
6330  The State Department told the Republican Natio...  
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...  
6332   Anti-Trump Protesters Are Tools of the Oligar...  
6333  ADDIS ABABA, Ethiopia —President Obama convene...  
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...  

[6335 rows x 2 columns]

In [6]:
y = df['label']

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 1, ..., 0, 1, 1])

In [8]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer,HashingVectorizer

In [9]:
df.isnull().sum()

title    0
text     0
label    0
dtype: int64

In [10]:
messages = df.copy()

In [11]:
messages

title  \
0                          You Can Smell Hillary’s Fear   
1     Watch The Exact Moment Paul Ryan Committed Pol...   
2           Kerry to go to Paris in gesture of sympathy   
3     Bernie supporters on Twitter erupt in anger ag...   
4      The Battle of New York: Why This Primary Matters   
...                                                 ...   
6330  State Department says it can't find emails fro...   
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...   
6332  Anti-Trump Protesters Are Tools of the Oligarc...   
6333  In Ethiopia, Obama seeks progress on peace, se...   
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                   text label  
0     Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1     Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2     U.S. Secretary of State John F. Kerry said Mon...  REAL  
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4     It's primary day in New York and front-runners...  REAL  
...                                                 ...   ...  
6330  The State Department told the Republican Natio...  REAL  
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...  FAKE  
6332   Anti-Trump Protesters Are Tools of the Oligar...  FAKE  
6333  ADDIS ABABA, Ethiopia —President Obama convene...  REAL  
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...  REAL  

[6335 rows x 3 columns]

In [12]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import re

In [13]:
ps = PorterStemmer()
corpus=[]
def transform_text(x):
#     corpus = []
    for i in range(0,len(x)):
        review = re.sub('[^a-zA-Z]',' ',messages['title'][i])
        review = review.lower()
        review = review.split()
    
        review = [ps.stem(word) for word in review if word not in stopwords.words('english')]
        review = ' '.join(review)
        corpus.append(review)
        
transform_text(messages)

In [14]:
corpus

['smell hillari fear',
 'watch exact moment paul ryan commit polit suicid trump ralli video',
 'kerri go pari gestur sympathi',
 'berni support twitter erupt anger dnc tri warn',
 'battl new york primari matter',
 'tehran usa',
 'girl horrifi watch boyfriend left facetim',
 'britain schindler die',
 'fact check trump clinton command chief forum',
 'iran reportedli make new push uranium concess nuclear talk',
 'three clinton iowa glimps fire elud hillari clinton campaign',
 'donald trump shockingli weak deleg game somehow got even wors',
 'strong solar storm tech risk today news oct video',
 'way america prepar world war',
 'trump take cruz lightli',
 'women lead differ',
 'shock michel obama hillari caught glamor date rape promot',
 'hillari clinton huge troubl america notic sick thing hidden pictur liberti writer news',
 'iran bill obama like',
 'chart explain everyth need know partisanship america',
 'slipperi slope trump propos ban muslim',
 'episod sunday wire hail deplor special g

In [15]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [16]:
# cv = CountVectorizer(max_features=4000,ngram_range=(1,3))
cv = TfidfVectorizer()
x = cv.fit_transform(corpus).toarray()

In [17]:
x.shape

(6335, 6884)

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=0)

In [20]:
x_train.shape,x_test.shape,y_test.shape,y_train.shape

((4244, 6884), (2091, 6884), (2091,), (4244,))

In [21]:
cv.get_feature_names()

C:\Users\mayan\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['aap',
 'abadi',
 'abandon',
 'abbi',
 'abc',
 'abduct',
 'abdullah',
 'abedin',
 'abil',
 'abl',
 'abnorm',
 'aboard',
 'abolish',
 'abort',
 'abridg',
 'abroad',
 'abrog',
 'absenc',
 'absente',
 'absolut',
 'abstain',
 'absurd',
 'absurdli',
 'abu',
 'abus',
 'abyss',
 'aca',
 'accept',
 'access',
 'accid',
 'accident',
 'accomplish',
 'accord',
 'account',
 'accur',
 'accus',
 'acela',
 'acheron',
 'achiev',
 'ackbar',
 'acknowledg',
 'aclu',
 'acquir',
 'acquisit',
 'acquit',
 'acquitt',
 'acr',
 'across',
 'act',
 'action',
 'activ',
 'activist',
 'actor',
 'actual',
 'acupunctur',
 'ad',
 'adam',
 'adamantli',
 'adapt',
 'add',
 'adderal',
 'addict',
 'address',
 'adelson',
 'adequ',
 'adhd',
 'adhm',
 'adjust',
 'admin',
 'administr',
 'admir',
 'admit',
 'admittedli',
 'adopt',
 'ador',
 'adpr',
 'adult',
 'advanc',
 'advantag',
 'advert',
 'advertis',
 'advic',
 'advis',
 'advisor',
 'advoc',
 'aerodynam',
 'afar',
 'affair',
 'affect',
 'affili',
 'affirm',
 'afford',
 'aff

In [22]:
cv.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.float64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 1),
 'norm': 'l2',
 'preprocessor': None,
 'smooth_idf': True,
 'stop_words': None,
 'strip_accents': None,
 'sublinear_tf': False,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'use_idf': True,
 'vocabulary': None}

In [23]:
df1 = pd.DataFrame(x_train,columns=cv.get_feature_names())
df1

aap  abadi  abandon  abbi  abc  abduct  abdullah  abedin  abil  abl  \
0     0.0    0.0      0.0   0.0  0.0     0.0       0.0     0.0   0.0  0.0   
1     0.0    0.0      0.0   0.0  0.0     0.0       0.0     0.0   0.0  0.0   
2     0.0    0.0      0.0   0.0  0.0     0.0       0.0     0.0   0.0  0.0   
3     0.0    0.0      0.0   0.0  0.0     0.0       0.0     0.0   0.0  0.0   
4     0.0    0.0      0.0   0.0  0.0     0.0       0.0     0.0   0.0  0.0   
...   ...    ...      ...   ...  ...     ...       ...     ...   ...  ...   
4239  0.0    0.0      0.0   0.0  0.0     0.0       0.0     0.0   0.0  0.0   
4240  0.0    0.0      0.0   0.0  0.0     0.0       0.0     0.0   0.0  0.0   
4241  0.0    0.0      0.0   0.0  0.0     0.0       0.0     0.0   0.0  0.0   
4242  0.0    0.0      0.0   0.0  0.0     0.0       0.0     0.0   0.0  0.0   
4243  0.0    0.0      0.0   0.0  0.0     0.0       0.0     0.0   0.0  0.0   

      ...  zika  zimbabw  zion  zionist  zip  zone  ztech  zuckerberg  zuess  \
0     ...   0.0      0.0   0.0      0.0  0.0   0.0    0.0         0.0    0.0   
1     ...   0.0      0.0   0.0      0.0  0.0   0.0    0.0         0.0    0.0   
2     ...   0.0      0.0   0.0      0.0  0.0   0.0    0.0         0.0    0.0   
3     ...   0.0      0.0   0.0      0.0  0.0   0.0    0.0         0.0    0.0   
4     ...   0.0      0.0   0.0      0.0  0.0   0.0    0.0         0.0    0.0   
...   ...   ...      ...   ...      ...  ...   ...    ...         ...    ...   
4239  ...   0.0      0.0   0.0      0.0  0.0   0.0    0.0         0.0    0.0   
4240  ...   0.0      0.0   0.0      0.0  0.0   0.0    0.0         0.0    0.0   
4241  ...   0.0      0.0   0.0      0.0  0.0   0.0    0.0         0.0    0.0   
4242  ...   0.0      0.0   0.0      0.0  0.0   0.0    0.0         0.0    0.0   
4243  ...   0.0      0.0   0.0      0.0  0.0   0.0    0.0         0.0    0.0   

      zulu  
0      0.0  
1      0.0  
2      0.0  
3      0.0  
4      0.0  
...    ...  
4239   0.0  
4240   0.0  
4241   0.0  
4242   0.0  
4243   0.0  

[4244 rows x 6884 columns]

### Multinomial Naive Baye's Algorithm

In [42]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()

In [43]:
from sklearn.metrics import accuracy_score,confusion_matrix
import itertools
import numpy as np


In [44]:
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)
score = accuracy_score(y_test,y_pred)
print(score)

0.8043998087039694


In [45]:
confusion_matrix(y_test,y_pred)

array([[763, 264],
       [145, 919]], dtype=int64)

### RandomForestClassifier

In [28]:
from sklearn.ensemble import RandomForestClassifier

In [29]:
# rf = RandomForestClassifier()

In [30]:
# rf.fit(x_train,y_train)
# y_pred = rf.predict(x_test)
# score = accuracy_score(y_test,y_pred)
# print(score)

### Decision Tree

In [31]:
from sklearn.tree import DecisionTreeClassifier

In [32]:
# dtr = DecisionTreeClassifier()
# dtr.fit(x_train,y_train)
# y_pred = dtr.predict(x_test)
# score = accuracy_score(y_test,y_pred)
# print(score)

### Support Vector Classifier

In [33]:
# from sklearn.svm import SVC

In [34]:
# svc = SVC()

In [35]:
# svc.fit(x_train,y_train)

SVC()

In [40]:
# y_pred = svc.predict(x_test)
# y_pred

array([1, 1, 0, ..., 1, 1, 0])

In [37]:
# score = accuracy_score(y_test,y_pred)
# print(score)

0.8216164514586323


In [46]:
import pickle

In [47]:
pickle.dump(cv,open('vectorizer.pkl','wb'))
pickle.dump(classifier,open('model.pkl','wb'))

In [ ]:
%%writefile app.py
import streamlit as st
import pickle
import re
from nltk.corpus import stopwords
import string
import nltk
from nltk.stem import PorterStemmer


cv = pickle.load(open('vectorizer.pkl','rb'))
svc = pickle.load(open('model.pkl','rb'))

st.title("Fake News Classifier")

input_news = st.text_area("Enter the title of the news")

if st.button('Predict'):

    # 1. preprocess
    ps = PorterStemmer()
    corpus = []


    def transform_text(x):
        #     corpus = []
#         for i in range(0, len(x)):
            review = re.sub('[^a-zA-Z]', ' ', x)
            review = review.lower()
            review = review.split()

            review = [ps.stem(word) for word in review if word not in stopwords.words('english')]
            review = ' '.join(review)
#             corpus.append(review)
            return review

    transform_text(input_news)
    transformed_news = transform_text(input_news)

    # 2. vectorize
    vector_input = cv.transform([transformed_news])

    # 3. predict
    result = svc.predict(vector_input)[0]
    # 4. display

    if result == 1:
        st.header('SPAM')
    else:
        st.header('Not Spam')



